# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-16 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='key',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
