# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-16 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20161216_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste',
            name='name',
            field=models.CharField(default='hello', max_length=64),
            preserve_default=False,
        ),
    ]
